export const REGION_MAPPINGS: Record<string, string[]> = {
  europe: [
    "albania",
    "andorra",
    "austria",
    "belarus",
    "belgium",
    "bosnia",
    "bulgaria",
    "croatia",
    "czech republic",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "iceland",
    "ireland",
    "italy",
    "latvia",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "malta",
    "moldova",
    "monaco",
    "montenegro",
    "netherlands",
    "norway",
    "poland",
    "portugal",
    "romania",
    "russia",
    "san marino",
    "serbia",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
    "switzerland",
    "ukraine",
    "united kingdom",
    "uk",
    "vatican city",
  ],
  asia: [
    "afghanistan",
    "armenia",
    "azerbaijan",
    "bahrain",
    "bangladesh",
    "bhutan",
    "brunei",
    "cambodia",
    "china",
    "cyprus",
    "georgia",
    "hong kong",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "israel",
    "japan",
    "jordan",
    "kazakhstan",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "lebanon",
    "malaysia",
    "maldives",
    "mongolia",
    "myanmar",
    "nepal",
    "north korea",
    "oman",
    "pakistan",
    "palestine",
    "philippines",
    "qatar",
    "saudi arabia",
    "singapore",
    "south korea",
    "sri lanka",
    "syria",
    "taiwan",
    "tajikistan",
    "thailand",
    "timor-leste",
    "turkey",
    "turkmenistan",
    "united arab emirates",
    "uzbekistan",
    "vietnam",
    "yemen",
  ],
  africa: [
    "algeria",
    "angola",
    "benin",
    "botswana",
    "burkina faso",
    "burundi",
    "cameroon",
    "cape verde",
    "central african republic",
    "chad",
    "comoros",
    "congo",
    "democratic republic of the congo",
    "djibouti",
    "egypt",
    "equatorial guinea",
    "eritrea",
    "ethiopia",
    "gabon",
    "gambia",
    "ghana",
    "guinea",
    "guinea-bissau",
    "ivory coast",
    "kenya",
    "lesotho",
    "liberia",
    "libya",
    "madagascar",
    "malawi",
    "mali",
    "mauritania",
    "mauritius",
    "morocco",
    "mozambique",
    "namibia",
    "niger",
    "nigeria",
    "rwanda",
    "senegal",
    "seychelles",
    "sierra leone",
    "somalia",
    "south africa",
    "south sudan",
    "sudan",
    "swaziland",
    "tanzania",
    "togo",
    "tunisia",
    "uganda",
    "zambia",
    "zimbabwe",
  ],
  "north america": [
    "canada",
    "united states",
    "usa",
    "mexico",
    "greenland",
    "bermuda",
    "saint pierre and miquelon",
  ],
  "central america": [
    "belize",
    "costa rica",
    "el salvador",
    "guatemala",
    "honduras",
    "nicaragua",
    "panama",
  ],
  caribbean: [
    "antigua and barbuda",
    "bahamas",
    "barbados",
    "cuba",
    "dominica",
    "dominican republic",
    "grenada",
    "haiti",
    "jamaica",
    "saint kitts and nevis",
    "saint lucia",
    "saint vincent and the grenadines",
    "trinidad and tobago",
  ],
  "south america": [
    "argentina",
    "bolivia",
    "brazil",
    "chile",
    "colombia",
    "ecuador",
    "guyana",
    "paraguay",
    "peru",
    "suriname",
    "uruguay",
    "venezuela",
  ],
  oceania: [
    "australia",
    "fiji",
    "kiribati",
    "marshall islands",
    "micronesia",
    "nauru",
    "new zealand",
    "palau",
    "papua new guinea",
    "samoa",
    "solomon islands",
    "tonga",
    "tuvalu",
    "vanuatu",
  ],
};
